### ISSUE TITLE
A couple of bugs...

### ISSUE THREAD

**Issue by Millennium-Eagle** [ExileLord/Open-GHTCP#4]
The program has a tendency to crash when trying to set the song preview when importing a song. Also, when you click and drag a song from the songlist to a setlist/tier, the song disappears from the songlist until you close and open the program again. These bugs are not in the original GHTCP, so they must have been introduced recently somehow. Other than that, it seems to work fine.

**Comment by ExileLord** [comment]
The former is in the original GHTCP. I have encountered it multiple times. With that said it is still something worth fixing. The latter is likely due to a change from .net that I haven't narrowed down enough yet. We do know about it though.

Please open these as separate individual issues rather than one big bug report. Thank you.
